# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278b18920da958c2491c5d188d7605681accf82715a873cb7dfda419152b478f570eff0bb10885d46eb618b40f2b25137556ed75d3eeef4dd4cd20065b18fc6a

test:
  secret_key_base: 899a72a32d8639a48aef87cbcc14ab1b6281bfc9f56d2eb4f723a9fe7c591a5961c0f72b9837eba145d4ac75db84e724ff03d52f51361bb207d47193481e9b7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
